spring.application.name=auth

# 1. URL e Credenciais (Estão certas!)
spring.datasource.url=jdbc:postgresql://navdata-db:5432/navdata_auth
spring.datasource.username=postgres
spring.datasource.password=Franc1sc0*123

# 2. CORREÇÃO: O Driver agora é do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. CORREÇÃO: O Dialeto (A língua que o Hibernate fala com o banco)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Manter o resto como está
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.time-zone=America/Sao_Paulo

# 4. ATENÇÃO: Sua porta mudou para 9090
server.port=8080

# Logs (Ótimo para vermos se o JWT e o Auth estão funcionando)
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG


jwt.secret=eT8ZxGjEnFvRBAFsWRA9ef0zK6wcnfOZ0DRUvMNwph97vdCBJAVcbBzjI3RtROzzlS/4XKMAs4rMBckP7R+NjQ==

GOOGLE_CLIENT_ID=1032687505128-ggm1fq9eeose7stjut82aibtbu2277tc.apps.googleusercontent.com